services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: nanostar_db
      MYSQL_ROOT_PASSWORD: nanostar_secret # 生产环境请修改并放入 .env
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306" # 映射出来方便你用 Navicat 等工具查看

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    build: .
    restart: always
    command: /app/entrypoint.sh
    volumes:
      - ./server:/app
    environment:
      - DJANGO_SETTINGS_MODULE=nanostar.settings
      - APP_SECRET_TOKEN=nanostar2026
      - TENCENT_MAP_API_KEY=QHABZ-H64CB-HQXUG-NVQJ5-PWYWO-FGBSG
      - IP_API_ENDPOINT=https://uapis.cn/api/v1/network/myip
      - IP_API_KEY=uapi-toxkaqcsejTkBG1XN1INY18GGQ5eiSsOWYiI9pAE
      - SUPERUSER_USERNAME=admin
      - SUPERUSER_PASSWORD=adminpassword123
    depends_on:
      - db
      - redis
    ports:
      - "1895:8000"  # [新增这一行] 将容器内的8000映射到宿主机的8000

volumes:
  mysql_data:
  redis_data: