# Generated by Django 5.2.15 on 2026-06-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('version_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_tracking_enabled', models.BooleanField(default=True)),
                ('distance_threshold', models.FloatField(default=500.0, help_text='拒绝访客的距离阈值(米)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.CharField(help_text='设备唯一标识', max_length=64, primary_key=True, serialize=False)),
                ('fcm_token', models.CharField(blank=True, help_text='Firebase推送令牌', max_length=255, null=True)),
                ('is_online', models.BooleanField(default=False, help_text='当前WS是否在线')),
                ('last_seen', models.DateTimeField(auto_now=True, help_text='最后活跃时间')),
                ('active_modules', models.JSONField(default=list, help_text='设备支持的能力清单')),
            ],
        ),
        migrations.CreateModel(
            name='VisitorRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, help_text='计算出的距离(米)', null=True)),
                ('timestamp', models.BigIntegerField(help_text='毫秒级时间戳')),
                ('is_success', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
