# Generated by Django 5.2.15 on 2026-06-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorrecord',
            name='module',
            field=models.CharField(default='tracking', help_text='模块名称，用于历史数据筛选', max_length=64),
        ),
    ]
