# Generated by Django 5.2.15 on 2026-06-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_visitorrecord_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorrecord',
            name='device_address',
            field=models.TextField(blank=True, default='', help_text='设备坐标逆地理编码地址'),
        ),
        migrations.AddField(
            model_name='visitorrecord',
            name='device_latitude',
            field=models.FloatField(blank=True, help_text='设备纬度', null=True),
        ),
        migrations.AddField(
            model_name='visitorrecord',
            name='device_longitude',
            field=models.FloatField(blank=True, help_text='设备经度', null=True),
        ),
        migrations.AddField(
            model_name='visitorrecord',
            name='visitor_latitude',
            field=models.FloatField(blank=True, help_text='访客纬度', null=True),
        ),
        migrations.AddField(
            model_name='visitorrecord',
            name='visitor_longitude',
            field=models.FloatField(blank=True, help_text='访客经度', null=True),
        ),
    ]
