# Generated by Django 5.2.15 on 2026-06-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_visitorrecord_device_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorrecord',
            name='visitor_address',
            field=models.TextField(blank=True, default='', help_text='访客坐标逆地理编码地址'),
        ),
    ]
