# Generated by Django 5.2.15 on 2026-07-01 06:52

import django.db.models.deletion
from django.db import migrations, models


def migrate_existing_comments(apps, schema_editor):
    """将 VisitorRecord.comment 中的历史评论迁移到 Comment 表"""
    VisitorRecord = apps.get_model('core', 'VisitorRecord')
    Comment = apps.get_model('core', 'Comment')
    for record in VisitorRecord.objects.exclude(comment=''):
        Comment.objects.create(
            visitor_record=record,
            fingerprint=record.fingerprint,
            content=record.comment,
            timestamp=record.timestamp,
        )


def reverse_migrate_comments(apps, schema_editor):
    """回滚：将 Comment 内容写回 VisitorRecord.comment（仅保留第一条）"""
    VisitorRecord = apps.get_model('core', 'VisitorRecord')
    Comment = apps.get_model('core', 'Comment')
    for record in VisitorRecord.objects.all():
        first_comment = Comment.objects.filter(visitor_record=record).order_by('created_at').first()
        if first_comment:
            record.comment = first_comment.content
            record.save(update_fields=['comment'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_visitorrecord_visitor_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_fingerprint', models.CharField(db_index=True, help_text='FingerprintJS 访客指纹', max_length=64, unique=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True, help_text='首次出现时间')),
                ('last_seen', models.DateTimeField(auto_now=True, help_text='最近出现时间')),
            ],
        ),
        migrations.AddField(
            model_name='appconfig',
            name='max_comments_per_record',
            field=models.PositiveIntegerField(default=3, help_text='同一访问记录最大评论数'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='show_past_comments',
            field=models.BooleanField(default=True, help_text='评论页是否展示历史评论列表'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='visit_cooldown_minutes',
            field=models.PositiveIntegerField(default=30, help_text='同一指纹访问冷却时间(分钟)'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='评论内容')),
                ('timestamp', models.BigIntegerField(help_text='毫秒级时间戳')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visitor_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.visitorrecord')),
                ('fingerprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='core.fingerprint')),
            ],
        ),
        migrations.AddField(
            model_name='visitorrecord',
            name='fingerprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='core.fingerprint'),
        ),
        migrations.RunPython(migrate_existing_comments, reverse_migrate_comments),
        migrations.RemoveField(
            model_name='visitorrecord',
            name='comment',
        ),
    ]
