# Generated by Django 5.2.15 on 2026-07-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fingerprint_remove_visitorrecord_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='show_all_history',
            field=models.BooleanField(default=False, help_text='历史评论是否显示该指纹全部记录下的留言'),
        ),
    ]
