# Generated by Django 5.2.15 on 2026-07-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_appconfig_show_all_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='show_total_visitors',
            field=models.BooleanField(default=False, help_text='成功页是否显示累计成功访客人数'),
        ),
    ]
