# Generated by Django 5.2.15 on 2026-07-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_appconfig_show_total_visitors'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='show_first_comments',
            field=models.BooleanField(default=False, help_text='首次成功访问时是否展示过去的留言'),
        ),
    ]
