# Generated by Django 5.2.15 on 2026-07-10 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_appconfig_show_first_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appconfig',
            options={'verbose_name': '应用配置', 'verbose_name_plural': '应用配置'},
        ),
    ]
