# Generated by Django 5.2.15 on 2026-07-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_appconfig_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='show_distance_on_failure',
            field=models.BooleanField(default=True, help_text='匹配失败时是否向客户端显示距离信息'),
        ),
    ]
