# Generated by Django 5.2.15 on 2026-07-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_appconfig_show_distance_on_failure'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='success_message',
            field=models.TextField(blank=True, default='', help_text='验证成功时在前端显示的自定义信息，支持HTML'),
        ),
    ]
