"""
Django settings for nanostar project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-lx71@99vvn4u7z8&(^wvwj0d+f&%l#h)5m=#f4_$fs2sug0-!r"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'daphne', # 接管 ASGI 服务 (必须在第一位)
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    # 我们的模块
    'core',
    'ws_gateway',
    'api',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "nanostar.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# WSGI_APPLICATION = "nanostar.wsgi.application"
ASGI_APPLICATION = 'nanostar.asgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("redis", 6379)], # 确保你的本地/服务器跑着 Redis
        },
    },
}
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'nanostar_db',
        'USER': 'root',
        'PASSWORD': 'nanostar_secret', # 必须与 compose 文件中一致
        'HOST': 'db',
        'PORT': '3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# 应用密钥 — WebSocket / HTTP API 鉴权共用
APP_SECRET_TOKEN = os.environ.get("APP_SECRET_TOKEN", "nanostar2026")

# 腾讯地图逆地理编码 API
TENCENT_MAP_GEOCODER_URL = os.environ.get(
    "TENCENT_MAP_GEOCODER_URL", "https://apis.map.qq.com/ws/geocoder/v1/"
)
TENCENT_MAP_API_KEY = os.environ.get("TENCENT_MAP_API_KEY", "")

# uapis.cn IP 查询 API（前端 JS 用）
IP_API_ENDPOINT = os.environ.get("IP_API_ENDPOINT", "https://uapis.cn/api/v1/network/myip")
IP_API_KEY = os.environ.get("IP_API_KEY", "")

# 静态文件请求的 URL 前缀
STATIC_URL = '/static/'

# 告诉 Django：运行 collectstatic 命令时，把所有 app 里的 static 文件统一搬到这个根目录
STATIC_ROOT = os.path.join(BASE_DIR, 'static')